server:
  port: 9000
spring:
  datasource:
    url: ${DB_URL:jdbc:oracle:thin:@localhost:1521/FREE}
    username: ${DB_AUTH_USER:SEGURIDAD_USER}
    password: ${DB_AUTH_PASS:SeguridadPass123}
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        default_schema: SEGURIDAD_USER
        format_sql: true
